FROM golang:1.20.1-alpine

# use local copy of Iter8 folder
ADD . /iter8

# Go to the Iter8 folder
WORKDIR "/iter8"

# Install Iter8
RUN go install 

# Download curl
RUN apk --no-cache add curl

WORKDIR /

