# Small linux image with iter8 binary
FROM debian:buster-slim

# Install curl
RUN apt-get update && apt-get install -y curl

# Download iter8 compressed binary
# use COPY instead of wget
COPY _dist/iter8-linux-amd64.tar.gz iter8-linux-amd64.tar.gz

# Extract iter8
RUN tar -xvf iter8-linux-amd64.tar.gz

# Extract iter8
RUN mv linux-amd64/iter8 /bin/iter8
